#!/bin/sh


pgrep -x sxhkd > /dev/null; (sxhkd >> /tmp/sxhkd-log.txt 2>&1) & 
pkill dunst; dunst &

# Terminate already running bar instances
# If all your bars have ipc enabled, you can use 
polybar-msg cmd quit
# Otherwise you can use the nuclear option:
killall -q polybar


xset -b
xset r rate 200 25;
setxkbmap -model pc104 -layout pl,ru -option grp:alt_shift_toggle;
setxkbmap -option caps:escape
xsetroot -cursor_name left_ptr


sh "$(dirname "$0")"/dump_disconnected_monitor.sh | tee $(mktemp /tmp/bspwm-dump.XXXXX.log)
sh "$(dirname "$0")"/multimonitor_setup.sh | tee $(mktemp /tmp/bspwm-multi.XXXXX.log)
pkill srandrd; srandrd bspc wm -r | tee $(mktemp /tmp/bspwm-srandrd.XXXXX.log)

nitrogen --restore &

# Launch bar on each monitor
(
polybar --list-monitors | while IFS= read line; do
    monitor=$(echo $line | cut -d':' -f1)
    bar=$([ ! -z $(echo $line | cut -d' ' -f3) ] && echo "primary" || echo "secondary")
    MONITOR=$monitor polybar $bar &
done
) &

bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# sonokai
bspc config normal_border_color   "#423f46" # bg3
bspc config active_border_color   "#423f46" # "#ef9062" # orange
bspc config focused_border_color  "#848089" # grey
bspc config presel_feedback_color "#848089"

bspc rule -a Nitrogen state=floating focus=on rectangle=500x500+300+300
bspc rule -a Pavucontrol state=pseudo_tiled focus=on
bspc rule -a Alacritty:Floating state=floating
bspc rule -a Alacritty:Pseudo state=pseudo_tiled
bspc rule -a SpeedCrunch state=floating
bspc rule -a Yad state=floating
bspc rule -a Dragon-drop sticky=on
bspc rule -a Java:java state=pseudo_tiled

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
