#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pkill dunst; dunst &
# pgrep -x stalonetray > /dev/null || stalonetray &
# ~/.config/lemonbar/lemonbar.sh &
#!/usr/bin/env bash

# Terminate already running bar instances
# If all your bars have ipc enabled, you can use 
polybar-msg cmd quit
# Otherwise you can use the nuclear option:
# killall -q polybar
# Launch bar1 and bar2
echo "---" | tee -a /tmp/polybar.log
polybar 2>&1 | tee -a /tmp/polybar.log & disown

# xdo above -t $(xdo id -n root) $(xdo id -n lemonbar)
# xdo above -t $(xdo id -n root) $(xdo id -n stalonetray)
# xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" $(xdo id -n stalonetray)

(
    xset r rate 200 25;
    xinput --set-prop 13 'libinput Accel Speed' -0.1
    setxkbmap -model pc104 -layout us,ru -option grp:alt_shift_toggle;
    xsetroot -cursor_name left_ptr;
) &

bspc monitor ^1 -d 1 2 3 4 5 6 7 8 9 0
bspc monitor ^2 -r

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# gruvbox
bspc config normal_border_color   "#1d2021"
bspc config active_border_color   "#fe8019"
bspc config focused_border_color  "#a89984"
bspc config presel_feedback_color "#8ec07c"

bspc rule -a Nitrogen state=floating focus=on rectangle=500x500+300+300
bspc rule -a Pavucontrol state=floating focus=on
bspc rule -a Alacritty:Floating:* state=floating
bspc rule -a SpeedCrunch state=floating
bspc rule -a Yad state=floating
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
