return {
--     {
--       "mrcjkb/rustaceanvim",
--       version = "^4", -- Recommended
--       ft = { "rust" },
--       dependencies = {
--        "williamboman/mason-lspconfig.nvim",
--       },
--       opts = {
--         server = {
--           on_attach = function(_, bufnr)
--             vim.keymap.set("n", "<a-cr>", function()
--               vim.cmd.RustLsp("codeAction")
--             end, { desc = "Code Action", buffer = bufnr })
--           end,
--           default_settings = {
--             -- rust-analyzer language server configuration
--             ["rust-analyzer"] = {
--               cargo = {
--                 allFeatures = true,
--                 loadOutDirsFromCheck = true,
--                 buildScripts = {
--                   enable = true,
--                 },
--               },
--               -- Add clippy lints for Rust.
--               checkOnSave = true,
--               procMacro = {
--                 enable = true,
--                 ignored = {
--                   ["async-trait"] = { "async_trait" },
--                   ["napi-derive"] = { "napi" },
--                   ["async-recursion"] = { "async_recursion" },
--                 },
--               },
--             },
--           },
--         },
--       },
--     },
}
