# colorscheme tender
# todo: also try monokai_pro!
[colors.primary]
background = '#282828'
foreground = '#eeeeee'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#c5152f'
green   = '#c9d05c'
yellow  = '#ffc24b'
blue    = '#b3deef'
magenta = '#d3b987'
cyan    = '#73cef4'
white   = '#eeeeee'

# Bright colors
[colors.bright]
black   = '#4c4c4c'
red     = '#f43753'
green   = '#c9d05c'
yellow  = '#ffc24b'
blue    = '#b3deef'
magenta = '#d3b987'
cyan    = '#73cef4'
white   = '#feffff'

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 13.5

[font.bold]
family = "Terminus"
style = "Bold"

[font.normal]
family = "Terminus"
style = "Regular"

[window]
dynamic_title = true
opacity = 0.92

[window.dimensions]
columns = 95
lines = 27
